import index from "./tree-versions.json";

/** Which generated tree a build should be drawn on, and how well it fits. */
export type TreeAsset = {
  /** The static SVG under /trees, generated by `npm run tree:svg`. */
  src: string;
  /** The version actually being drawn, which is not always the one asked for. */
  version: string;
  /**
   * False when the build's own tree version has not been generated and it is
   * being drawn on a later one. Node ids are stable across versions but their
   * positions are not — about a third of an old build's nodes sit somewhere
   * else on a current tree — so this is shown to the reader rather than
   * quietly papered over.
   */
  exact: boolean;
};

const VERSIONS = (index.versions as { version: string }[]).map((entry) => entry.version);

/**
 * Numeric, so 3.9 sorts below 3.16 rather than above it. An event's alternate
 * tree ("3.28.alternate") is never the fallback: its ascendancies are not the
 * game's, and "3.29.alternate" would otherwise sort above "3.29".
 */
function newest(): string | null {
  return (
    VERSIONS.filter((version) => /^[\d.]+$/.test(version))
      .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))
      .pop() ?? null
  );
}

/**
 * Pick the tree to draw a build on.
 *
 * An exact version match is the only correct answer, and generating one is a
 * single command — `npm run tree:svg -- 3.25` — so the fallback exists for the
 * gap between archiving a character and remembering to run it, not as the
 * normal path.
 *
 * A build from the game's own endpoints carries no version at all: the API
 * reports what a character has allocated today against whatever tree is live,
 * so the newest is the right tree for it and counts as exact.
 */
export function treeAsset(treeVersion?: string | null): TreeAsset | null {
  const latest = newest();
  if (!latest) return null;
  const asked = treeVersion?.trim();
  if (!asked) return { src: `/trees/${latest}.svg`, version: latest, exact: true };
  if (VERSIONS.includes(asked)) return { src: `/trees/${asked}.svg`, version: asked, exact: true };
  return { src: `/trees/${latest}.svg`, version: latest, exact: false };
}

/** Every version generated so far, for a test or a report. */
export function generatedTreeVersions(): string[] {
  return [...VERSIONS];
}
